title: aaayejaaaye
author: AJ
email:
description: > # this means to ignore newlines until "show_excerpts:"
  Welcome, I'm AJ. I am passionate about AR/VR and the role
  it will play in society.
  I've dedicated this blog to AR game development, emerging tech, software and all things related to learning as much as I can about
  augmented reality and virtual reality.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
  #  twitter: jekyllrb
    github: aaayejaaaye
  #  dribbble: jekyll
  #  facebook: jekyll
  #  flickr: jekyll
    instagram: aaayejaaaye
  #  linkedin: jekyll
    pinterest: aaayejaaaye
  #  telegram: jekyll
  #  googleplus: +jekyll
  #  microdotblog: jekyll
  #  keybase: jekyll


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

jekyll-amazon:
  locale: 'ja'  # label's language. default: 'en'
  country: 'jp' # with the two character country code of their Amazon
                # Affiliate account (e.g. `'us'` for United States).
                # default: 'us'
                # 'br'/'ca'/'cn'/'de'/'es'/'fr'/'in'/'it'/'jp'/'mx/'uk'/'us'
  template_dir: '_templates' # original template directory

plugins:
 - jekyll-feed
 - jekyll-seo-tag
